# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '0210CralingQuiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Kanna','~>5.0.0'
  # Pods for 0210CralingQuiz

end
